# Generated by Django 4.1.2 on 2022-12-31 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Departments',
            new_name='Department',
        ),
    ]
